url: "https://stardoods.github.io"
title: starlands

collections:
  characters:
    output: true
    permalink: /characters/:title/
  the-songbird:
    output: true
    permalink: /the-songbird/:title/

defaults:
  -
    scope:
      path: ""
      type: "characters"
    values: 
      layout: "character"
  -
    scope:
      path: ""
      type: "the-songbird"
    values: 
      layout: "the-songbird"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true

exclude:
  - docs/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
