url: "https://stardoods.github.io"
title: starlands


collections:
  characters:
    output: true
    permalink: /characters/:name/

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"


# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true


# Exclude from processing

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
